# Generated by Django 5.0.4 on 2024-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('start_location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('total_time', models.IntegerField()),
            ],
            options={
                'db_table': 'ride',
                'managed': True,
            },
        ),
    ]
