# Generated by Django 5.0.4 on 2024-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('total_time', models.IntegerField(null=True)),
            ],
        ),
    ]
