# Generated by Django 5.0.3 on 2024-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0002_ride_time_alter_ride_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
