# Generated by Django 5.0.3 on 2024-04-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0003_alter_ride_ride_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride_time',
        ),
    ]
