# Generated by Django 5.0.3 on 2024-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0004_delete_ride_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_data',
            fields=[
                ('ride_id', models.AutoField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('station', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('total_time', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
