# Generated by Django 5.0.3 on 2024-04-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0005_ride_data_delete_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_data',
            name='ride_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
