# Generated by Django 5.0.3 on 2024-05-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeRide', '0002_ride_station_name_ride_user_alter_ride_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='total_time',
            field=models.FloatField(default=0, null=True),
        ),
    ]
