# Generated by Django 5.0.4 on 2024-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_time', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'payment_info',
                'managed': True,
            },
        ),
    ]
