# Generated by Django 5.0.4 on 2024-04-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Info', '0001_initial'),
    ]

    operations = [
    ]
