# Generated by Django 5.0.3 on 2024-04-20 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Info', '0003_shoyeb_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_info',
            name='total_time',
        ),
        migrations.AddField(
            model_name='payment_info',
            name='cost_per_min',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
