# Generated by Django 5.0.4 on 2024-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Info', '0003_shoyeb_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_min', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Payment_Info',
        ),
    ]
