# Generated by Django 5.0.3 on 2024-04-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeRide', '0002_ride_station_name_ride_user_alter_ride_station'),
        ('Payment_Info', '0004_remove_payment_info_total_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='ride',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MakeRide.ride'),
        ),
    ]
