# Generated by Django 5.0.4 on 2024-04-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Info', '0004_payment_delete_payment_info'),
    ]

    operations = [
    ]
