# Generated by Django 5.0.3 on 2024-03-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
