# Generated by Django 5.0.3 on 2024-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(default='2024-03-23', verbose_name='join date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('none', 'Select Type'), ('Rider', 'Rider'), ('Admin', 'Admin')], default='none', max_length=10),
        ),
    ]
