# Generated by Django 5.0.3 on 2024-03-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_customuser_join_date_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='join_date',
        ),
    ]
