# Generated by Django 5.0.3 on 2024-04-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_customuser_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
