# Generated by Django 5.0.4 on 2024-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('Rewards_id', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.IntegerField()),
            ],
            options={
                'db_table': 'rewards',
                'managed': True,
            },
        ),
    ]
