# Generated by Django 5.0.4 on 2024-04-22 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0002_rewards_payment_alter_rewards_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='user',
            field=models.ManyToManyField(related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
