# Generated by Django 5.0.4 on 2024-04-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike_station',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='bike_station',
            table='bike_station',
        ),
    ]
