# Generated by Django 5.0.4 on 2024-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Station', '0002_alter_bike_station_options_alter_bike_station_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_station',
            name='Station_ID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
