# Generated by Django 5.0.3 on 2024-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Station', '0003_alter_bike_station_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_station',
            name='Station_ID',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
