# Generated by Django 5.0.3 on 2024-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_alter_station_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_data',
            fields=[
                ('Station_ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Station_Name', models.CharField(max_length=20)),
                ('Number_of_Bikes', models.IntegerField()),
                ('Station_Status', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
