# Generated by Django 5.0.3 on 2024-04-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_alter_station_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={},
        ),
    ]
